### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by scarlehoff** [N3PDF/vegasflow#62]
Basically at it stands `VegasFlow` should work with python 3.9 out of the box, the only thing stopping it from working is the fact that TensorFlow (https://github.com/tensorflow/tensorflow/issues/44485) won't support official pip packages for python 3.9 for a while.

The pip package works perfectly fine with python 3.9 so if you have your own installation of Tensorflow working (for instance from your OS vendor) you can simply do

```bash
pip install vegasflow --no-deps
```

**Comment by mayou36** [comment]
TensorFlow 2.5 will have the 3.9 support, it just got merged into the nightlies: https://github.com/tensorflow/tensorflow/issues/44485#issuecomment-797037619
